Games/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

# Upload images
from django.conf.urls.static import static
from django.conf import settings

from django.views.generic import TemplateView
from base.views import IndexRedirectView
from gameplace.views import DragLetterTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index', TemplateView.as_view(template_name='index.html'), name='index'),
    path('', IndexRedirectView.as_view(), name='indexredirect'),
    path('dragletterdemo', DragLetterTemplateView.as_view(), name='dragletterdemo'),
    path('access/',include(('access.urls','access'), namespace='access')),
    path('words/', include(('words.urls','words'), namespace='words')),
    path('gameplace/', include(('gameplace.urls','gameplace'),namespace='gameplace')),
    path('gamerplace/', include(('gamerplace.urls','gamerplace'),namespace='gamerplace')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

access/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import reverse_lazy

from .views import UserCreateView, UserUpdateView, UserPaswordUpdateView, PersonCreateView, PersonUpadateView

urlpatterns = [

    path('', TemplateView.as_view(template_name='access/index.html'), name='index'),
    path('login/', LoginView.as_view(template_name = 'access/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='index'), name='logout'),
    path('newuser/', UserCreateView.as_view(), name='newuser'),
    path('updateuser/', UserUpdateView.as_view(), name='updateuser' ),
    path('updatepassword/', UserPaswordUpdateView.as_view(), name='updatepassword'),

    # pasword
    path('password-reset/', PasswordResetView.as_view(email_template_name='access/password_reset_email.html' , success_url=reverse_lazy("access:password_reset_done")), name='passwordreset'),
    path("password-reset/done/", PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>", PasswordResetConfirmView.as_view(success_url=reverse_lazy("access:password_reset_complete")), name="password_reset_confirm"),
    path("password-reset-complete/", PasswordResetCompleteView.as_view(), name="password_reset_complete"),

    path('newpersonaldata/', PersonCreateView.as_view(), name='newpersonaldata'),
    path('updatepersonaldata/', PersonUpadateView.as_view(), name='updatepersonaldata'),


]

access/models.py
from django.db import models
from django.conf import settings

from dropbox.exceptions import ApiError
import traceback

class Person(models.Model):
    user  = models.OneToOneField(settings.AUTH_USER_MODEL, verbose_name='User', on_delete=models.CASCADE, primary_key=True)
    name  = models.CharField('Name', max_length=200)
    photo = models.ImageField('Photo', upload_to='images/', max_length=500, null=True, blank=True)
    birth = models.DateTimeField('Birth')

    # Fields to backup control
    created = models.DateTimeField('Created', auto_now_add=True)
    modified = models.DateTimeField('Modified', auto_now=True)

    class Meta:
        verbose_name        = 'Person'
        verbose_name_plural = 'Persons'

    def get_photo_url(self):
        try:
            return self.photo.url
        except ApiError as e:
            traceback.print_exc()
            return None

    def __str__(self):
        return self.name

access/forms.py
# -*- coding: utf-8 -*-

from django.contrib.auth.forms import UserCreationForm
from django import forms

from django.contrib.auth import get_user_model


User = get_user_model()


class UserAdminCreationForm(UserCreationForm):

    class Meta:
            model = User
            fields = ['username', 'email']

class UserAdminForm(forms.ModelForm):

    class Meta:
            model = User
            fields = ['username', 'email', 'is_active', 'is_staff']

access/views.py
from django.shortcuts import render
from dropbox.exceptions import ApiError
import traceback
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, FormView
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import UserAdminCreationForm
from .models import Person

class UserCreateView(CreateView):
    model         = get_user_model()
    form_class    = UserAdminCreationForm
    template_name = 'access/new_user.html'
    success_url   = reverse_lazy('indexredirect')

class UserUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'access/update_user.html'
    model = get_user_model()
    success_url = reverse_lazy('index')
    fields = ['username','email']

    def get_object(self):
        return self.request.user

class UserPaswordUpdateView(LoginRequiredMixin, FormView):
    form_class = PasswordChangeForm
    template_name = 'access/update_user_password.html'
    success_url = reverse_lazy('indexredirect')

    def form_valid(self, form):
        form_valid = super(UserPaswordUpdateView, self).form_valid(form)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(self.request, user)
        return form_valid

    def get_form_kwargs(self):
        kwargs = super(UserPaswordUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class PersonCreateView (LoginRequiredMixin, CreateView):
    model = Person
    template_name = 'access/createupdate.html'
    fields = ['name', 'birth', 'photo']
    success_url = reverse_lazy('indexredirect')

    def get_context_data(self, **kwargs):
        ctx = super(PersonCreateView, self).get_context_data(**kwargs)
        ctx['title'] = 'Please complete the Registration'
        return ctx

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(PersonCreateView, self).form_valid(form)

class PersonUpadateView (LoginRequiredMixin, UpdateView):
    model = Person
    template_name = 'access/createupdate.html'
    fields = ['name', 'birth', 'photo']
    success_url = reverse_lazy('indexredirect')

    def get_object(self):
        person = Person.objects.get(user = self.request.user)
        if (person.photo != None):
            try:
                person.photo.url
            except ApiError as e:
                traceback.print_exc()
                person.photo = None
            except ValueError as e:
                # Prevent person.image == None
                pass
        return person

    def get_context_data(self, **kwargs):
        ctx = super(PersonUpadateView, self).get_context_data(**kwargs)
        ctx['title'] = 'Cadastro'
        return ctx

access/templates/access/createupdate.html
{% extends 'base.html' %}

{% load static %}

{% load widget_tweaks %}


{% block title %}{{title}} | {{block.super}}{% endblock %}

{% block content %}
<header>
  <h3>{{title}}</h3>
</header>
<section class="row">
  <aside class="col-md-6 col-md-offset-3">
      <img id="id_photo_img" class="img" src="{% if object.get_photo_url != None %}{{object.photo.url}}{% else %}{% static 'images/generic-avatar.png' %}{% endif %}" alt="photo">
  </aside>
  <main class="col-md-6 col-md-offset-3">
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
          {{ error }}
        </div>
      {% endfor %}
      <fieldset>
        {% for field in form %}
          <div class="form-group{% if field.errors %} has-error {% endif %}">
            <label for="{{ field.auto_id }}" class="control-label">{{ field.label }}</label>
            <div class="">
              {% render_field field class="form-control" %}
              {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
          <div class="form-group">
            <div class="col-md-9 col-md-offset-3">
              <button type="submit" class="btn btn-primary">Registrar</button>
            </div>
          </div>
      </fieldset>
    </form>
  </main>
</section>

<script type="text/javascript">
  // showPhoto
  showPhoto();

  // Date time to date treatment.
  // to solve the time problem with time in a html date field.
  birth = document.getElementById('id_birth');
  value = birth.value;
  birth.type = 'date';
  birth.value = value.substring(0,10); // eliminate the time;
</script>

{% endblock %}

access/templates/access/index.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Conta | {{block.super}}{% endblock %}

{% block content %}
  <header>
    <h1>Meu Cadastro</h1>
  </header>
  <section>
    <ul class="navbar-nav">
      <li class="nav-item"><a href="{% url 'access:updateuser' %}" class="nav-link">User Update</a></li>
      <li class="nav-item"><a href="{% url 'access:updatepassword' %}">Password Update</a></li>
      <li class="nav-item"><a href="{% url 'access:updatepersonaldata' %}">Personal Data</a></li>
    </ul>
  </section>
{% endblock %}

access/templates/access/login.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Entrar | {{block.super}}{% endblock %}

{% block content %}
  <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
          <div class="page-header">
              <h1>Entrar</h1>
          </div>
          <form class="form-horizontal" method="post">
              {% csrf_token %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error }}
                </div>
              {% endfor %}
              <fieldset>
                  <div class="form-group{% if form.username.errors %} has-error {% endif %}">
                    <label for="{{ form.username.auto_id }}" class="col-sm-3 control-label">{{ form.username.label }}</label>
                    <div class="col-sm-9">
                      {% render_field form.username class="form-control" %}
                      {% for error in form.username.errors %}
                        <span class="help-block">{{ error }}</span>
                      {% endfor %}
                    </div>
                  </div>
                  <div class="form-group{% if form.password.errors %} has-error {% endif %}">
                    <label for="{{ form.password.auto_id }}" class="col-sm-3 control-label">{{ form.password.label }}</label>
                    <div class="col-sm-9">
                      {% render_field form.password class="form-control" %}
                      {% for error in form.password.errors %}
                        <span class="help-block">{{ error }}</span>
                      {% endfor %}
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-9 col-sm-offset-3">
                      <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                    <div class="col-sm-9 col-sm-offset-3">
                      <a href="{% url 'access:passwordreset' %}">Forgot password?</a>
                    </div>
                  </div>
              </fieldset>
          </form>
      </div>
  </div>
{% endblock %}

access/templates/access/new_person.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}{{title}} | Cadastro{{block.super}}{% endblock %}

{% block content %}
<header>
  <h3>Please complete the Registration</h3>
</header>
<section>
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for error in form.non_field_errors %}
      <div class="alert alert-danger">
        {{ error }}
      </div>
    {% endfor %}
    <fieldset>
      {% for field in form %}
        <div class="form-group{% if field.errors %} has-error {% endif %}">
          <label for="{{ field.auto_id }}" class="control-label">{{ field.label }}</label>
          <div class="">
            {% render_field field class="form-control" %}
            {% for error in field.errors %}
              <span class="help-block">{{ error }}</span>
            {% endfor %}
          </div>
        </div>
      {% endfor %}
        <div class="form-group">
          <div class="col-md-9 col-md-offset-3">
            <button type="submit" class="btn btn-primary">Register</button>
          </div>
        </div>
    </fieldset>
  </form>
</section>

{% endblock %}

access/templates/access/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'access:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

access/templates/access/update_user.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Novo Usuário | {{block.super}}{% endblock %}

{% block content %}
  <div class="row">
      <div class="col-md-8 col-md-offset-2">
          <div class="page-header">
              <h1>Alterar dados de Usuário</h1>
          </div>
          <form class="form-horizontal" action="" method="post">
                {% csrf_token %}
                <fieldset>
                    {% for field in form %}
                    <div class="form-group{% if field.errors %} has-error{% endif %}">
                      <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                      <div class="col-md-9">
                        {% render_field field class='form-control' %}
                        {% for error in field.errors %}
                        <span class="help-block">{{ error }}</span>
                        {% endfor %}
                      </div>
                    </div>
                    {% endfor %}
                    <div class="form-group">
                      <div class="col-md-9 col-md-offset-3">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                      </div>
                    </div>
                </fieldset>
          </form>
      </div>
  </div>
{% endblock %}

access/templates/access/update_user_password.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Novo Usuário | {{block.super}}{% endblock %}

{% block content %}
  <div class="row">
      <div class="col-md-8 col-md-offset-2">
          <div class="page-header">
              <h1>Alterar Senha</h1>
          </div>
          <form class="form-horizontal" action="" method="post">
                {% csrf_token %}
                <fieldset>
                    {% for field in form %}
                    <div class="form-group{% if field.errors %} has-error{% endif %}">
                      <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                      <div class="col-md-9">
                        {% render_field field class='form-control' %}
                        {% for error in field.errors %}
                        <span class="help-block">{{ error }}</span>
                        {% endfor %}
                      </div>
                    </div>
                    {% endfor %}
                    <div class="form-group">
                      <div class="col-md-9 col-md-offset-3">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                      </div>
                    </div>
                </fieldset>
          </form>
      </div>
  </div>
{% endblock %}