Games/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

# Upload images
from django.conf.urls.static import static
from django.conf import settings

from django.views.generic import TemplateView
from base.views import IndexRedirectView
from gameplace.views import DragLetterTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index', TemplateView.as_view(template_name='index.html'), name='index'),
    path('', IndexRedirectView.as_view(), name='indexredirect'),
    path('dragletterdemo', DragLetterTemplateView.as_view(), name='dragletterdemo'),
    path('access/',include(('access.urls','access'), namespace='access')),
    path('words/', include(('words.urls','words'), namespace='words')),
    path('gameplace/', include(('gameplace.urls','gameplace'),namespace='gameplace')),
    path('gamerplace/', include(('gamerplace.urls','gamerplace'),namespace='gamerplace')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gameplace/urls.py
# -*- coding: utf-8 -*-

from django.urls import path

from .views import (
    PersonDataileView,
    MasterCreateView,
    MasterDetailView,
    MasterUpdateView,
    MasterDeleteView,
    GamerCreateView,
    GamerUpdateView,
    GamerPasswordUpdateView,
    MasterGamerDetailView,
    MasterGamerDeleteView,
    GamesDetailView,
    DragLetterFormView,
    DragLetterTemplateView,
)


urlpatterns = [

    path('', PersonDataileView.as_view(), name='index'),
    path('newavatar', MasterCreateView.as_view(), name='newmaster'),
    path('<slug:slug>/masterplace', MasterDetailView.as_view(), name='master'),
    path('<slug:slug>/updateavatar', MasterUpdateView.as_view(), name='updatemaster'),
    path('<slug:slug>/deleteavatar', MasterDeleteView.as_view(), name='deletemaster'),
    path('<slug:slugmaster>/newgamer', GamerCreateView.as_view(), name='newgamer'),
    path('<slug:slugmaster>/<int:pk>/updategamer', GamerUpdateView.as_view(), name='updategamer'),
    path('<slug:slugmaster>/<int:pk>/updategamerpassword', GamerPasswordUpdateView.as_view(), name='updategamerpassword'),
    path('<slug:slugmaster>/<int:pk>/mastergamerplace', MasterGamerDetailView.as_view(), name='mastergamer'),
    path('<slug:slugmaster>/<int:pk>/deletemastergamer', MasterGamerDeleteView.as_view(), name='deletemastergamer'),

    path('<int:pk>/games', GamesDetailView.as_view(), name='games'),
    path('<int:pk>/dragletter', DragLetterFormView.as_view(), name='dragletter'),

]

gamerplace/urls.py
# -*- coding: utf-8 -*-

from django.urls import path


from gamerplace.views import index, MyDictionary

urlpatterns = [
    path('<int:pk>', index.as_view(), name='index'),
    path('<int:pk>/mydictionary', MyDictionary.as_view(), name='mydictionary'),
]

gamerplace/models.py
from django.db import models

# Create your models here.

gamerplace/views.py
from django.shortcuts import render, get_object_or_404

from gameplace.models import Gamer

from django.contrib.auth.models import User
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

class index(LoginRequiredMixin, DetailView):

    template_name = 'gamerplace/index.html'
    model = Gamer

    def get_object(self):
        return get_object_or_404(Gamer, user=self.request.user, pk=self.kwargs['pk'])

class MyDictionary(LoginRequiredMixin, DetailView):

    template_name = 'gamerplace/mydictionary.html'
    model = Gamer

    def get_object(self):
        return get_object_or_404(Gamer, user=self.request.user, pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super(MyDictionary, self).get_context_data(**kwargs)
        context['words'] = kwargs['object'].word_set.all()
        return context

gamerplace/templates/gamerplace/index.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}{{title}} {{object.nickname}}'s place | {{block.super}}{% endblock %}

{% block content %}
<header>
  <h3>GAMER PLACE</h3>
</header>
<article class="">
  <h4>{{object.nickname}}</h4>
  {% if object.get_avatar_url != None %}<img class="avatar_img" src="{{object.avatar.url}}" alt="">{% endif %}
  <ul>
    <li><a href="{% url 'gameplace:dragletter' object.pk %}">Play</a></li>
    <li><a href="{% url 'gamerplace:mydictionary' object.pk %}">My dictionary</a></li>
  </ul>
</article>
<aside class="">
  <div class="row line">
    <div class="col-9">
      Word
    </div>
    <div class="col-3">
      Rights
    </div>
  </div>
  {% for right in object.getRights %}
    <div class="row line">
      <div class="col-9">
        {{right.word}}
      </div>
      <div class="col-3">
        {{right.number}}
      </div>
    </div>
  {% endfor %}
</aside>
<section class="galery">
</section>

{% endblock %}

gamerplace/templates/gamerplace/mydictionary.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}{{title}} {{object.nickname}}'s place | {{block.super}}{% endblock %}

{% block content %}
<script type="text/javascript">

</script>
<header>
  <h3>GAMER PLACE</h3>
</header>
<article class="">
  <h4>{{object.nickname}}</h4>
  {% if object.get_avatar_url != None %}<img class="avatar_img" src="{{object.avatar.url}}" alt="">{% endif %}
  <ul>
    <li><a href="{% url 'gamerplace:index' object.pk %}">return</a></li>
  </ul>
</article>
<aside>
  {% include 'words/dictionary.html' %}
</aside>
<section class="galery">
</section>

{% endblock %}