Games/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

# Upload images
from django.conf.urls.static import static
from django.conf import settings

from django.views.generic import TemplateView
from base.views import IndexRedirectView
from gameplace.views import DragLetterTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index', TemplateView.as_view(template_name='index.html'), name='index'),
    path('', IndexRedirectView.as_view(), name='indexredirect'),
    path('dragletterdemo', DragLetterTemplateView.as_view(), name='dragletterdemo'),
    path('access/',include(('access.urls','access'), namespace='access')),
    path('words/', include(('words.urls','words'), namespace='words')),
    path('gameplace/', include(('gameplace.urls','gameplace'),namespace='gameplace')),
    path('gamerplace/', include(('gamerplace.urls','gamerplace'),namespace='gamerplace')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

access/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import reverse_lazy

from .views import UserCreateView, UserUpdateView, UserPaswordUpdateView, PersonCreateView, PersonUpadateView

urlpatterns = [

    path('', TemplateView.as_view(template_name='access/index.html'), name='index'),
    path('login/', LoginView.as_view(template_name = 'access/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='index'), name='logout'),
    path('newuser/', UserCreateView.as_view(), name='newuser'),
    path('updateuser/', UserUpdateView.as_view(), name='updateuser' ),
    path('updatepassword/', UserPaswordUpdateView.as_view(), name='updatepassword'),

    # pasword
    path('password-reset/', PasswordResetView.as_view(email_template_name='access/password_reset_email.html' , success_url=reverse_lazy("access:password_reset_done")), name='passwordreset'),
    path("password-reset/done/", PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>", PasswordResetConfirmView.as_view(success_url=reverse_lazy("access:password_reset_complete")), name="password_reset_confirm"),
    path("password-reset-complete/", PasswordResetCompleteView.as_view(), name="password_reset_complete"),

    path('newpersonaldata/', PersonCreateView.as_view(), name='newpersonaldata'),
    path('updatepersonaldata/', PersonUpadateView.as_view(), name='updatepersonaldata'),


]

base/models.py
from django.db import models

gameplace/models.py
from django.db import models
from django.conf import settings
from django.db.models import Q

from dropbox.exceptions import ApiError
import traceback

class Master(models.Model):
    user      = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário', on_delete=models.CASCADE)
    slug      = models.SlugField('Slug', max_length=200, default='slug')
    nickname  = models.CharField('Nick', max_length=200)
    avatar    = models.ImageField('Avatar', upload_to='images/', max_length=500, null=True, blank=True)

    # Fields to backup control
    created = models.DateTimeField('Created', auto_now_add=True)
    modified = models.DateTimeField('Modified', auto_now=True)

    class Meta:
        verbose_name        = 'Master'
        verbose_name_plural = 'Masters'
        unique_together     = ['user','slug']

    def getGamers(self, authorized=True):
        return Gamer.objects.filter(
            Q(master = self) |
            Q(gamermaster__master = self, gamermaster__authorized = authorized)
        )

    def get_avatar_url(self):
        try:
            return self.avatar.url
        except ApiError as e:
            traceback.print_exc()
            return None

    def __str__(self):
        return self.nickname

class Gamer(models.Model):
    user          = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='User', on_delete=models.CASCADE)
    master        = models.ForeignKey(Master, verbose_name='Master', on_delete=models.CASCADE)
    nickname      = models.CharField('Nick', max_length=200)
    avatar        = models.ImageField('Avatar', upload_to='images/', max_length=500, null=True, blank=True)
    othersMasters = models.ManyToManyField(Master, through='GamerMaster', related_name='otherMasters')


    # Fields to backup control
    created = models.DateTimeField('Created', auto_now_add=True)
    modified = models.DateTimeField('Modified', auto_now=True)

    class Meta:
        verbose_name        = 'Gamer'
        verbose_name_plural = 'Gamers'

    def getRights(self):
        return self.right_set.filter(user=self.user)

    def get_avatar_url(self):
        try:
            return self.avatar.url
        except ApiError as e:
            traceback.print_exc()
            return None

    def __str__(self):
        return self.nickname

class Fan(models.Model):
    user      = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário', on_delete=models.CASCADE)
    gamer     = models.ForeignKey(Gamer, verbose_name='Masters', on_delete=models.CASCADE)
    nickname  = models.CharField('Nick', max_length=200)
    avatar    = models.ImageField('Avatar', upload_to='images/', max_length=500, null=True, blank=True)

    # Fields to backup control
    created = models.DateTimeField('Created', auto_now_add=True)
    modified = models.DateTimeField('Modified', auto_now=True)

    class Meta:
        verbose_name        = 'Fan'
        verbose_name_plural = 'Fans'

    def get_avatar_url(self):
        try:
            return self.avatar.url
        except ApiError as e:
            traceback.print_exc()
            return None

    def __str__(self):
        return self.nickname

class GamerMaster(models.Model):
    gamer      = models.ForeignKey('Gamer', verbose_name='gamer', on_delete=models.CASCADE)
    master     = models.ForeignKey('Master', verbose_name='master', on_delete=models.CASCADE)
    authorized = models.BooleanField('authorized', default=False)

    # Fields to backup control
    created = models.DateTimeField('Created', auto_now_add=True)
    modified = models.DateTimeField('Modified', auto_now=True)

    def __str__(self):
        return str(self.gamer) + ' + ' + str(self.master)

base/views.py
# -*- coding: utf-8 -*-


from django.shortcuts import render
from django.views.generic.base import RedirectView
from django.urls import reverse

from access.models import Person
from gameplace.models import Master, Gamer

class IndexRedirectView(RedirectView):

    pattern_name = 'index'
    query_string = False

    def get_redirect_url(self, *args, **kwargs):
        if (self.request.user.is_authenticated):
            try:
                person = Person.objects.get(user=self.request.user)
            except:
                return reverse('access:newpersonaldata')

            # Try a Master
            masters = Master.objects.filter(user=self.request.user)
            # If the user has a Master he or she goes to the Master Place.
            if (masters):
                return reverse('gameplace:index')

            # Try a Gamer
            gamers = Gamer.objects.filter(user=self.request.user)
            # if the user has a Gamer he/she goes to the Game Place.
            if (gamers):
                return reverse('gamerplace:index', kwargs={'pk':gamers[0].pk})

            # If user do not have neither a master neither a gamer he will invited to create an avatar (Master).
            return reverse('gameplace:newmaster')

        return super().get_redirect_url(*args, **kwargs)

base/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
 <title>{% block title %}Gustavo's Games{% endblock %} </title>
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

<!-- Read core functions -->
<script type="text/javascript" src='{% static "script/base.js" %}'></script>

 <link rel="stylesheet" href="{% static 'style/style.css' %}" />

</head>
<body>

<div class="jumbotron text-center" style="margin-bottom:0">
 <h1>Gustavo's Games</h1>
 <h2>Play learning</h2>
 <p></p>
</div>

<nav class="navbar navbar-expand-sm navbar-dark">
 <a class="navbar-brand" href="{% url 'indexredirect' %}">Home</a>
 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
   <span class="navbar-toggler-icon"></span>
 </button>
 <div class="collapse navbar-collapse" id="collapsibleNavbar">
<!--
   <ul class="navbar-nav">
     <li class="nav-item">
       <a class="nav-link" href="#">Opção 1</a>
     </li>
     <li class="nav-item">
       <a class="nav-link" href="#">Link</a>
     </li>
     <li class="nav-item">
       <a class="nav-link" href="#">Link</a>
     </li>
   </ul>
 -->
   <div class="nav-item">
      {% if user.is_authenticated %}
        <span class="nav-brand glyphicon glyphicon-log-in">{{user}}</span>
    </div>
    <div class="">
      <ul class="navbar-nav">
        {% if user.master_set.all.0 %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'gameplace:index' %}">Master Place</a>
          </li>
        {% endif %}
        {% if user.gamer_set.all.0 %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'indexredirect' %}">Gamer Place</a>
          </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'access:index' %}">User Place</a>
        </li>
      </ul>
    </div>
    <div class="nav-item">
        <a id="logout" class="nav-link" href=" {% url 'access:logout' %} ">logout</a>
      {% else %}
        <a id="login" class="nav-link" href="{% url 'access:login' %}">login</a>
    </div>
    <div class="nav-item">
        <a id="novousuario" class="nav-link" href="{% url 'access:newuser' %}">New user</a>
      {% endif %}
    </div>
 </div>
</nav>

<div class="container margin-top" style="margin-top:30px">
{% block content %}

{% endblock %}
</div>

<footer></footer>

</body>
</html>

base/templates/base_game.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
 <title>{% block title %}Gustavo's Games{% endblock %} </title>
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

 <link rel="stylesheet" href="{% static 'style/style.css' %}" />


</head>
<body>

<nav class="navbar navbar-expand-sm navbar-dark">
 <a class="navbar-brand" href="{% url 'indexredirect' %}">Home</a>
 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
   <span class="navbar-toggler-icon"></span>
 </button>
 <div class="collapse navbar-collapse" id="collapsibleNavbar">
<!--
   <ul class="navbar-nav">
     <li class="nav-item">
       <a class="nav-link" href="#">Opção 1</a>
     </li>
     <li class="nav-item">
       <a class="nav-link" href="#">Link</a>
     </li>
     <li class="nav-item">
       <a class="nav-link" href="#">Link</a>
     </li>
   </ul>
 -->
   <div class="nav-item">
      {% if user.is_authenticated %}
        <span class="nav-brand glyphicon glyphicon-log-in">{{user}}</span>
    </div>
    <div class="">
      <ul class="navbar-nav">
        {% if user.master_set.all.0 %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'gameplace:index' %}">Master Place</a>
          </li>
        {% endif %}
        {% if user.gamer_set.all.0 %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'indexredirect' %}">Gamer Place</a>
          </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'access:index' %}">User Place</a>
        </li>
      </ul>
    </div>
    <div class="nav-item">
        <a id="logout" class="nav-link" href=" {% url 'access:logout' %} ">logout</a>
      {% else %}
        <a id="login" class="nav-link" href="{% url 'access:login' %}">login</a>
    </div>
    <div class="nav-item">
        <a id="novousuario" class="nav-link" href="{% url 'access:newuser' %}">New user</a>
      {% endif %}
    </div>
 </div>
</nav>

<div class="container margin-top" style="margin-top:30px">
{% block content %}

{% endblock %}
</div>

<footer></footer>

</body>
</html>

base/templates/index.html
{% extends 'base.html' %}

{% block title %}{{block.super}}{% endblock %}

{% block content %}
<aside class="">
  try <a href="{% url 'dragletterdemo' %}">drag letters</a>
</aside>
<article class="">
  <header>
    <h1>Why this app</h1>
  </header>
  <main>
    <p>With the pandemic, I started to actively participate in my son's literacy. I realized that he was having difficulties, showed a lack of interest in online classes, I had to pressure him, constantly calling his attention.
He found all reasons to leave the class that had only an hour duration!</p>
    <p>I remember, sometimes, having to leave to avoid exploding with rage. I even kicked a pilates ball away, such was my frustration.</p>
    <p>On the other hand, I learned a lot from the classes. I quickly realized that I should be as discreet as possible and let him have the maximum autonomy in class, my presence there, although necessary, often hindered the class.</p>
    <p>Gradually, I also began to understand the process and method used by teachers: The children chose a project, which was actually a theme. The teachers chose the words from the vocabulary used by the children themselves. Then they (children) started to create an illustrated dictionary. Each word was written by the teacher in front of the children, who then should write the word and draw it.</p>
    <p>I realized that he needed to practice more, as he quickly forgot the words he trained. In his duties, he kept trying to guess. I saw that he was not doing well. So, in addition to creating exercises on paper, I decided to create this program as a complement to the method.</p>
  </main>
  <footer></footer>
</article>
<article class="">
  <header>
    <h1>Outcome</h1>
  </header>
  <main>
    <p>I did a little test, for a few days, he trained four words.</p>
    <p>I liked what I saw, he didn't spend too much time in front of my cell phone, just long enough to learn to identify words.</p>
    <p>After the first test, my father was admitted - he is doing well - and I spent the days in the hospital with my brother.</p>
    <p>Due to the increased risk of getting covid, I have not seen my son, he has stayed at his mother's house.</p>
    <p>Thus, he did not use more Gustavo's Games.</p>
    <p>For my surprise, his mother told me over the phone that the word he liked most was the bee!</p>
    <p>I looked at the statistics of the program and found what I already imagined, the word he had trained the most (the words are offered at random) was precisely bee.</p>
  </main>
</article>
{% endblock %}