Games/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

# Upload images
from django.conf.urls.static import static
from django.conf import settings

from django.views.generic import TemplateView
from base.views import IndexRedirectView
from gameplace.views import DragLetterTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index', TemplateView.as_view(template_name='index.html'), name='index'),
    path('', IndexRedirectView.as_view(), name='indexredirect'),
    path('dragletterdemo', DragLetterTemplateView.as_view(), name='dragletterdemo'),
    path('access/',include(('access.urls','access'), namespace='access')),
    path('words/', include(('words.urls','words'), namespace='words')),
    path('gameplace/', include(('gameplace.urls','gameplace'),namespace='gameplace')),
    path('gamerplace/', include(('gamerplace.urls','gamerplace'),namespace='gamerplace')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gameplace/urls.py
# -*- coding: utf-8 -*-

from django.urls import path

from .views import (
    PersonDataileView,
    MasterCreateView,
    MasterDetailView,
    MasterUpdateView,
    MasterDeleteView,
    GamerCreateView,
    GamerUpdateView,
    GamerPasswordUpdateView,
    MasterGamerDetailView,
    MasterGamerDeleteView,
    GamesDetailView,
    DragLetterFormView,
    DragLetterTemplateView,
)


urlpatterns = [

    path('', PersonDataileView.as_view(), name='index'),
    path('newavatar', MasterCreateView.as_view(), name='newmaster'),
    path('<slug:slug>/masterplace', MasterDetailView.as_view(), name='master'),
    path('<slug:slug>/updateavatar', MasterUpdateView.as_view(), name='updatemaster'),
    path('<slug:slug>/deleteavatar', MasterDeleteView.as_view(), name='deletemaster'),
    path('<slug:slugmaster>/newgamer', GamerCreateView.as_view(), name='newgamer'),
    path('<slug:slugmaster>/<int:pk>/updategamer', GamerUpdateView.as_view(), name='updategamer'),
    path('<slug:slugmaster>/<int:pk>/updategamerpassword', GamerPasswordUpdateView.as_view(), name='updategamerpassword'),
    path('<slug:slugmaster>/<int:pk>/mastergamerplace', MasterGamerDetailView.as_view(), name='mastergamer'),
    path('<slug:slugmaster>/<int:pk>/deletemastergamer', MasterGamerDeleteView.as_view(), name='deletemastergamer'),

    path('<int:pk>/games', GamesDetailView.as_view(), name='games'),
    path('<int:pk>/dragletter', DragLetterFormView.as_view(), name='dragletter'),

]

words/urls.py
from django.urls import path


from .views import (
    WordListView,
    WordCreateView,
    WordUpadateView,
    WordDeleteView,
)

urlpatterns = [

    path('', WordListView.as_view(), name='words'),
    path('<slug:slugmaster>/<int:pkgamer>/newword/', WordCreateView.as_view(),name='newword'),
    path('<slug:slugmaster>/<int:pkgamer>/<int:pk>/updateword/', WordUpadateView.as_view(), name='updateword'),
    path('<slug:slugmaster>/<int:pkgamer>/<int:pk>/deleteword/', WordDeleteView.as_view(), name='deleteword'),

]

words/models.py
from django.db import models
from gameplace.models import Master, Gamer
from django.conf import settings

from dropbox.exceptions import ApiError
import traceback


class Word(models.Model):

    gamer  = models.ForeignKey(Gamer, verbose_name='Gamer', on_delete=models.CASCADE, null=True, blank=True)
    word   = models.CharField('Word', max_length=200)
    image  = models.ImageField('Image', upload_to='images/', max_length=500, null=True, blank=True)

    # Fields to backup control
    created = models.DateTimeField('Created', auto_now_add=True)
    modified = models.DateTimeField('Modified', auto_now=True)

    class Meta:
        verbose_name        = 'Word'
        verbose_name_plural = 'Words'

    def get_image_url(self):
        try:
            return self.image.url
        except ApiError as e:
            traceback.print_exc()
            return None


    def __str__(self):
        return self.word

class Right(models.Model):
    user   = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='User', on_delete=models.CASCADE)
    gamer  = models.ForeignKey(Gamer, verbose_name='Gamer', on_delete=models.CASCADE)
    word   = models.ForeignKey(Word, verbose_name='Word', on_delete=models.CASCADE)
    number = models.IntegerField('Rights', default=0)

    # Fields to backup control
    created = models.DateTimeField('Created', auto_now_add=True)
    modified = models.DateTimeField('Modified', auto_now=True)

    class Meta:
        verbose_name        = 'Right'
        verbose_name_plural = 'Rights'
        unique_together = [['user', 'gamer', 'word']]

    def __str__(self):
        return self.word.word + " " + str(self.number)

gameplace/forms.py
from django import forms

class WordIdForm(forms.Form):

    word_id = forms.IntegerField()

gameplace/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, CreateView, DetailView, ListView, UpdateView, DeleteView, FormView
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.db.models import Q

from access.forms import UserAdminCreationForm

from .models import Master, Gamer
from .forms import WordIdForm
from access.models import Person
from words.models import Word, Right
from django.contrib.auth.models import User

from dropbox.exceptions import ApiError
import traceback

import random

class PersonDataileView(LoginRequiredMixin, DetailView):

    model = Person
    template_name = 'gameplace/index.html'

    def get_object(self):
        return get_object_or_404(Person, user = self.request.user)

    def get_context_data(self, **kwargs):
        context = super(PersonDataileView, self).get_context_data(**kwargs)
        context['masters'] = Master.objects.filter(user = self.request.user)
        return context



"""class IndexListView(LoginRequiredMixin, ListView):

    model = Master
    template_name = 'gameplace/index.html'

    def get_queryset(self):
        return Master.objects.filter(user = self.request.user)"""

class MasterCreateView(LoginRequiredMixin, CreateView):

    template_name = 'gameplace/new_master.html'
    fields = ['nickname', 'slug', 'avatar']
    success_url = reverse_lazy('gameplace:index')

    def get_queryset(self):
        return Master.objects.filter(user = self.request.user)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(MasterCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(MasterCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Create a fun new avatar'

        return context

class MasterDetailView(LoginRequiredMixin, DetailView):

    template_name = 'gameplace/master_place.html'
    model         = Master

    def get_context_data(self, **kwargs):
        context = super(MasterDetailView, self).get_context_data(**kwargs)
        gamers = self.object.getGamers()

        context['gamers'] = gamers
        return context

class MasterUpdateView(LoginRequiredMixin, UpdateView):

    template_name = 'gameplace/new_master.html'
    fields = ['nickname', 'slug', 'avatar']
    success_url = reverse_lazy('gameplace:index')

    def get_object(self):
        master = get_object_or_404(Master, user=self.request.user, slug = self.kwargs['slug'])

        if (master.avatar != None):
            try:
                master.avatar.url
            except ApiError as e:
                traceback.print_exc()
                master.avatar = None
            except ValueError as e:
                # Prevent master.image == None
                pass

        return master

    def get_context_data(self, **kwargs):
        context = super(MasterUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Update Avatar'

        return context

class MasterDeleteView(LoginRequiredMixin, DeleteView):

    template_name = 'gameplace/delete_master.html'
    success_url = reverse_lazy('gameplace:index')

    def get_object(self):
        return get_object_or_404(Master, user=self.request.user, slug = self.kwargs['slug'])

class GamerCreateView(LoginRequiredMixin, CreateView):

    model         = get_user_model()
    template_name = 'gameplace/new_user.html'
    form_class    = UserAdminCreationForm
    success_url    = reverse_lazy('gameplace:index') # that will be changed to gamer update


    def form_valid(self, form):
        if form.is_valid():
            gamersmaster = get_object_or_404(Master, slug = self.kwargs['slugmaster'], user = self.request.user)
            formvalid = super(GamerCreateView, self).form_valid(form)
            gamer = Gamer(
                user     = form.instance,
                master   = gamersmaster,
                nickname = form.instance.username,
                avatar   = 'images/generic-avatar.png'
            )
            gamer.save()
        return formvalid

    def get_success_url(self):

        url = reverse_lazy('gameplace:master', kwargs = {'slug':self.kwargs['slugmaster']})
        return url

class GamerUpdateView(LoginRequiredMixin, UpdateView):

    #model = Gamer
    template_name = 'gameplace/createupdate.html'
    fields = ['nickname', 'avatar']

    def get_success_url(self):
        url = reverse_lazy('gameplace:master', kwargs = {'slug':self.kwargs['slugmaster']})
        return url

    def get_object(self):

        master = get_object_or_404(Master, user=self.request.user, slug = self.kwargs['slugmaster'])
        gamer  = get_object_or_404(Gamer, master = master, pk=self.kwargs['pk'])

        if (gamer.avatar != None):
            try:
                gamer.avatar.url
            except ApiError as e:
                traceback.print_exc()
                gamer.avatar = None
            except ValueError as e:
                # Prevent master.image == None
                pass

        return gamer

class GamerPasswordUpdateView(LoginRequiredMixin, FormView):

    form_class = PasswordChangeForm
    template_name = 'access/update_user_password.html'
    success_url = reverse_lazy('indexredirect')

    def form_valid(self, form):

        # Get gamer user
        master = get_object_or_404(Master, slug = self.kwargs['slugmaster'])
        gamer  = get_object_or_404(Gamer, master = master, pk = self.kwargs['pk'])

        # Reset password
        #password = self.request.POST.get('id_old_password')
        #gamer.user.set_password(password)
        #gamer.user.save()
        form = PasswordChangeForm(gamer.user, data = self.request.POST)

        form_valid = super(GamerPasswordUpdateView, self).form_valid(form)
        if form.is_valid():
            user = form.save()
            # update_session_auth_hash(self.request, user)
        else:
            print('\n\n\nform invalid\n\n\n')
        return form_valid

    def get_form_kwargs(self):
        kwargs = super(GamerPasswordUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class MasterGamerDetailView(LoginRequiredMixin, DetailView):

    template_name = 'gameplace/master_gamer_place.html'

    def get_object(self):
        master = get_object_or_404(Master, user=self.request.user, slug=self.kwargs['slugmaster'])
        return get_object_or_404(master.getGamers(), pk=self.kwargs['pk'])


class MasterGamerDeleteView(LoginRequiredMixin, DeleteView):

    template_name = 'gameplace/delete_master_gamer.html'
    # success_url   = reverse_lazy('gameplace:index')

    def get_success_url(self):
        return reverse_lazy('gameplace:master', kwargs={'slug':self.kwargs['slugmaster']})

    def get_object(self):
        master = get_object_or_404(Master, slug=self.kwargs['slugmaster'])
        return get_object_or_404(Gamer, master=master, pk=self.kwargs['pk'])

class GamesDetailView(LoginRequiredMixin, DetailView):

        template_name = 'gameplace/games.html'

        def get_object(self):
            try:
                return Gamer.objects.get(user=self.request.user, pk=self.kwargs['pk'])
            except:
                # the master can play the games like he is one of his gamers,
                # but will be registered on his user
                return get_object_or_404(
                    Gamer.objects.filter(
                        Q(master__user=self.request.user) |
                        Q(othersMasters__user=self.request.user)
                    ),
                    pk=self.kwargs['pk']
                )

def getGamer(user, pk):
    # get the gamer only if the user is the user gamer or the user master of the gamer.
    try:
        gamer = Gamer.objects.get(user=user, pk=pk)
    except:
        # the master can play the games like he is one of his gamers,
        # but will be registered on his user
        gamer =  get_object_or_404(
            Gamer.objects.filter(
                Q(master__user=user) |
                Q(othersMasters__user=user)
            ),
            pk=pk
        )
    return gamer

class DragLetterFormView(LoginRequiredMixin, FormView):

    #template_name = 'gameplace/drag_letter.html'
    template_name = "gameplace/drag_letter_2.html"

    form_class = WordIdForm

    def setup(self, request, *args, **kwargs):
        super(DragLetterFormView,self).setup(request, *args, **kwargs)
        self.gamer = getGamer(self.request.user, self.kwargs['pk'])

    def get_context_data(self, **kwargs):

        user = self.request.user

        """
        Select some random word
        """

        # Get all Gamer's word
        words = Word.objects.filter(gamer=self.gamer)
        word = ''
        if (words.count()>1):
            word_number = random.randrange(words.count())
            word = words[word_number]
        elif (words.count()==1):
            word = words[0]

        # get Rights number to word
        try:
            rights = word.right_set.get(user=self.request.user).number
        except Exception as e:
            rights = 0

        context = super(DragLetterFormView, self).get_context_data(**kwargs)
        context['title'] = 'Drag Letter'

        context['gamer'] = self.gamer


        if (word==''):
            context['randomWord'] = ''
            return context

        context['word']  = word

        target = word.word

        """
        Rules for the Target
        -----
            1. Dragletter show each letters of the word to be a target;
            2. If a gamer has right number equal 5 for a word dragletters show the word with an simbol insted first letter.

gameplace/templates/gameplace/createupdate.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}{{title}} | {{block.super}}{% endblock %}

{% block content %}
<header>
  <h3>{{title}}</h3>
</header>
<section>
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for error in form.non_field_errors %}
      <div class="alert alert-danger">
        {{ error }}
      </div>
    {% endfor %}
    <fieldset>
      {% for field in form %}
        <div class="form-group{% if field.errors %} has-error {% endif %}">
          <label for="{{ field.auto_id }}" class="control-label">{{ field.label }}</label>
          <div class="">
            {% render_field field class="form-control" %}
            {% for error in field.errors %}
              <span class="help-block">{{ error }}</span>
            {% endfor %}
          </div>
        </div>
      {% endfor %}
        <div class="form-group">
          <div class="col-md-9 col-md-offset-3">
            <button type="submit" class="btn btn-primary">Registrar</button>
          </div>
        </div>
    </fieldset>
  </form>
</section>

{% endblock %}

gameplace/templates/gameplace/delete_master.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}{{object.nickname}} | {{block.super}}{% endblock %}

{% block content %}
<header>
  <h3>Delete {{object.nickname}}</h3>
</header>
<section class="">
  <article class="">

    <form class="form-horizontal" method="post">
      {% csrf_token %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
          {{ error }}
        </div>
      {% endfor %}
      <fieldset>
          <div class="form-group">
            <div class="col-md-9 col-md-offset-3">
              <p>Do you want to delete avatar {{ object.nickname }}?<br/>
              <button type="submit" class="btn btn-primary">Yes</button>
              <a href="{% url 'index' %}" type="button" class="btn btn-primary">No</a>
            </div>
          </div>
      </fieldset>
    </form>

  </article>
</section>

{% endblock %}

gameplace/templates/gameplace/delete_master_gamer.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}{{object.nickname}} | {{block.super}}{% endblock %}

{% block content %}
<header>
  <h3>Delete {{object.nickname}}</h3>
</header>
<section class="">
  <article class="">

    <form class="form-horizontal" method="post">
      {% csrf_token %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
          {{ error }}
        </div>
      {% endfor %}
      <fieldset>
          <div class="form-group">
            <div class="col-md-9 col-md-offset-3">
              <p>Do you want to delete the gamer {{ object.nickname }}?<p/>
              <p>If you do this, all historic about this gamer will be lost.</p>

              <button type="submit" class="btn btn-primary">Yes</button>
              <a href="{% url 'index' %}" type="button" class="btn btn-primary">No</a>
            </div>
          </div>
      </fieldset>
    </form>

  </article>
</section>

{% endblock %}

gameplace/templates/gameplace/drag_letter.html
{% extends 'gameplace/gamer_place_base.html' %}

{% load static %}

{% load widget_tweaks %}

{% block title %}Drag Letter | {{block.super}} {% endblock %}

{% block game %}


<style media="screen">

  img {
    display: block;
    width:150px;
    margin-left:  auto;
    margin-right: auto;
  }

  table {
    font-size: 50px;
    min-width: 250px;
    margin-left:  auto;
    margin-right: auto;

  }

  .font {
    font    : bold 100% Comic, sans-serif;
  }

  .inner {
    color   : #252525;
    text-shadow: 1px 1px #F0F0FF, -3px -3px 1px #101010;
  }

</style>

<script type="text/javascript" src="{% static "script/draggin.js" %}"></script>

<header>
  <h3>Drag Letters</h3>
</header>
<section>
  <span style="display:none" id='word'>{{word.word}}</span>
  <div class="img_square">

  </div>
  {% if word %}
    <table>
      <tr>
        {% for letter in word.word %}
          <td><span id="{{letter}}" class="font inner target"><script>document.write('{{target}}'[{{forloop.counter0}}]);</script></span></td>
        {% endfor %}
      </tr>
    </table>
    <table>
      <tr>
        {% for letter in randomWord %}
          <td><span class="font draggable" id="{{letter}}">{{letter}}</span></td>
        {% endfor %}
      </tr>

    </table>
    <form id="drag_letters_form" action="" method="post">
      {% csrf_token %}

      <input type="hidden" name="word_id" id="word_id" value="{{word.id}}">


    </form>
  {% else %}
    <div class="alert alert-dark">
      <p>Sorry.</p>
      <p>There is no word.</p>
      <p>Asck for the master to insert some one.</p>
      <a href="{% url 'indexredirect' %}" class="button">Click here to return.</a>
    </div>
  {% endif %}
  {% if word.get_image_url != None %}
    <img src="{{word.image.url}}" alt="">
  {% endif %}
</section>

{% endblock %}

gameplace/templates/gameplace/drag_letter_2.html
{% extends 'gameplace/game.html' %}

{% load static %}

{% load widget_tweaks %}

{% block title %}Drag Letter | {{block.super}} {% endblock %}

{% block game %}
  {% if word %}
    <script type="text/javascript" src='{% static "script/dragletter2/dragLetters2.js" %}'></script>
    <script type="text/javascript" src='{% static "script/dragletter2/animation.js" %}'></script>
    <script type="text/javascript" src='{% static "script/dragletter2/collision.js" %}'></script>
    <script type="text/javascript" src='{% static "script/dragletter2/keyboard.js" %}'></script>
    <script type="text/javascript" src='{% static "script/dragletter2/background.js" %}'></script>
    <script type="text/javascript" src='{% static "script/dragletter2/wordImage.js" %}'></script>
    <script type="text/javascript" src='{% static "script/dragletter2/hero.js" %}'></script>
    <script type="text/javascript" src='{% static "script/dragletter2/target.js" %}'></script>
    <script type="text/javascript" src='{% static "script/dragletter2/letter.js" %}'></script>
    <script type="text/javascript" src='{% static "script/dragletter2/visualTouch.js" %}'></script>
    <script type="text/javascript" src='{% static "script/dragletter2/spritesheet.js" %}'></script>
    <script type="text/javascript" src='{% static "script/dragletter2/spriteover.js" %}'></script>

    <style media="screen">
      html, body {
        overflow: hidden;
      }
    </style>

    <canvas id="canvas" width="290" height="400"></canvas>


    <form id="drag_letters_form" action="" method="post">

      {% csrf_token %}

      <input type="hidden" name="word_id" id="word_id" value="{{word.id}}">


    </form>

    <script type="text/javascript">


      var conclude = function() {

        document.getElementById("drag_letters_form").submit();
      }

      document.body.onload = function() {
        // Canvas e Context
        var canvas = document.getElementById('canvas');
        var drag = new DragLetters(document, canvas, {'imgSrc':{% if word.image.url != None and word.get_image_url %}'{{ word.image.url|escapejs }}'{% else %}"{% static 'images/generic-avatar.png' %}"{% endif %}, 'text':'{{word.word}}','target':'{{target}}','randomWord':'{{randomWord}}'});
     }
    </script>
  {% else %}
      <div class="alert alert-dark">
        <p>Sorry.</p>
        <p>There is no word.</p>
        <p>Asck for the master to insert some one.</p>
        <a href="{% url 'indexredirect' %}" class="button">Click here to return.</a>
      </div>
  {% endif %}
{% endblock %}

gameplace/templates/gameplace/game.html
{% extends 'base_game.html' %}

{% load static %}

{% load widget_tweaks %}

{% block title %}{{gamer.nickname}}'s place | {{block.super}}{% endblock %}

{% block content %}
 {% block game %}{% endblock %}
{% endblock %}

gameplace/templates/gameplace/games.html
{% extends 'gameplace/gamer_place_base.html' %}

{% load widget_tweaks %}

{% block title %}Drag Letter | {{block.super}}{% endblock %}

{% block game %}
<article class="">
  <header>
    <h3>Games</h3>
  </header>
  <main>
    <a href="{% url 'gameplace:dragletter' object.pk %}">Drag Letter</a>
  </main>
</article>


{% endblock %}

gameplace/templates/gameplace/index.html
{% extends 'base.html' %}

{% load static %}

{% load widget_tweaks %}

{% block title %}{{title}} | {{block.super}}{% endblock %}

{% block content %}
<header>
  <h3>Gamer PLACE</h3>
</header>
<article class="">
  <p>{{object.name}}</p>
  {% if object.get_photo_url != None %}
    <img src="{{object.photo.url}}" alt="avatar" class="img_panel">
  {% else %}
    <img src="{% static '/images/generic-avatar.png' %}" alt="avatar" class="img_panel">
  {% endif %}
</article>

<section>
  <header>
    <h2>Avatars</h2>
  </header>
  <div class="galery">
    {% for master in masters %}

      <article class="panel">

        <h3>{{master.nickname}}</h3>
        <a href="{% url 'gameplace:master' master.slug %}">
          {% if master.get_avatar_url != None %}
            <img src="{{master.avatar.url}}" alt="{{master.nickname}}" class="img_panel">
          {% else %}
            <img src="{% static '/images/generic-avatar.png' %}" alt="{{master.nickname}}" class="img_panel">
          {% endif %}
        </a>
      </article>

    {% endfor %}
    <article class="panel">
      <h3>New Avatar</h3>
      <a href="{% url 'gameplace:newmaster' %}">
        <img src="{% static '/images/generic-avatar.png' %}" alt="new avatar" class="img_panel">
      </a>
    </article>
  </div>
</section>

{% endblock %}

gameplace/templates/gameplace/master_gamer_place.html
{% extends 'base.html' %}

{% load static %}

{% load widget_tweaks %}

{% block title %}{{object.nickname}}'s place | {{block.super}}{% endblock %}

{% block content %}
<header>
    <h3>{% if object.master.avatar.url != None and object.master.get_avatar_url%}<img class="micro_img" src="{{ object.master.avatar.url }}" alt="">{%endif%} {{ object.master.nickname }}</h3>
  <h3>{{object.nickname}}'s Place</h3>
</header>
<section>
  <article class="">

    {% if object.avatar.url != None and object.get_avatar_url %}
      <img class="avatar_img" src="{{object.avatar.url}}" alt="{{object.nickname}}">
    {%else%}
      <img class="avatar_img" src="{% static 'images/generic-avatar.png' %}" alt="generic">
    {%endif%}

    <ul>
      <li><a href="{% url 'gameplace:games' object.pk %}">Play</a></li>
      <li><a href="{% url 'gameplace:updategamer' object.master.slug object.pk %}">Edit</a></li>
      <li><a href="{% url 'gameplace:updategamerpassword' object.master.slug object.pk %}">Change Password</a></li>
      <li><a href="{% url 'gameplace:deletemastergamer' object.master.slug object.pk %}">Delete</a></li>
    </ul>

  </article>
</section>
<section class="">
  <header>
    <h3>Results</h3>
  </header>
  {% for right in object.getRights %}
    <div class="row line">
      <div class="col-9">
        {{right.word}}
      </div>
      <div class="col-3">
        {{right.number}}
      </div>
    </div>
  {% endfor %}
</section>
<section class="">
  <header>
    <h3>Words</h3>
  </header>
  <div class="galery">
    <article class="panel">
      <h3>New Word</h3>
      <a href="{% url 'words:newword' view.kwargs.slugmaster object.pk %}">
        <img class="img_panel" src="{% static '/images/generic-avatar.png' %}" alt="new word">
      </a>
    </article>
    {% for word in object.word_set.all %}
      <article class="panel">
        <h3>{{word}}</h3>
        <a href="{% url 'words:updateword' view.kwargs.slugmaster object.pk word.pk %}">
          {% if word.image.url != None and word.get_image_url %}
            <img class="img_panel" src="{{word.image.url}}" alt="{{word}}">
          {% else %}
            <img class="img_panel" src="{% static '/images/generic-avatar.png' %}" alt="generic">
          {% endif %}
        </a>
        <footer style="padding:3px;">
          <a href="{% url 'words:deleteword' view.kwargs.slugmaster object.pk word.pk %}" class="btn btn-secondary">Delete word</a>
        </footer>

      </article>
    {% endfor %}
  </div>
</section>

{% endblock %}

gameplace/templates/gameplace/master_place.html
{% extends 'base.html' %}

{% load static %}

{% load widget_tweaks %}

{% block title %}{{object.nickname}} | {{block.super}}{% endblock %}

{% block content %}
<header>
  <h3>{{object.nickname}}'s Place</h3>
</header>
<section>
  <article class="">

    {% if object.get_avatar_url != None %}
      <img class="avatar_img" src="{{object.avatar.url}}" alt="{{object.nickname}}" class='img_panel'>
      {% else %}
        <img src="{% static 'images/generic-avatar.png' %}" alt="generic" class='img_panel'>
    {% endif %}

    <ul>
      <li><a href="{% url 'gameplace:updatemaster' object.slug %}">Edit</a></li>
      <li><a href="{% url 'gameplace:deletemaster' object.slug %}">Delete</a></li>
    </ul>

  </article>
</section>
<section class="galery">
  <header>
    <h3>Gamers</h3>
  </header>
    {% for gamer in gamers %}
      <article class="panel">

        <h3>{{gamer.nickname}}</h3>
        <a href="{% url 'gameplace:mastergamer' master.slug gamer.pk %}">
          {% if gamer.get_avatar_url != None %}
            <img src="{{gamer.avatar.url}}" alt="{{gamer.avatar.url}}" class='img_panel'>
          {% else %}
            <img src="{% static 'images/generic-avatar.png' %}" alt="generic" class='img_panel' >
          {% endif %}
        </a>
      </article>
    {% endfor %}
  <article class="panel">
    <h3>New Gamer</h3>
    <a href="{% url 'gameplace:newgamer' object.slug %}">
      <img src="{% static '/images/generic-avatar.png' %}" class='img_panel' alt="new gamer">
    </a>
  </article>
</section>

{% endblock %}